### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by johnwc** [ectoflow/vue-stripe-js#1]
Would be possible to add screenshots for the examples in the markdown?

**Comment by softbeehive** [comment]
It's possible, and would be nice to have, but readme is pretty long already. I'll consider adding visual examples if it grows. This library is pretty small at the moment, therefore I didn't build a dedicated website.

You can clone this repo, install dependencies and run `yarn dev` or `npm run dev`
You'll be able to play with the demo of the card element

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1150276/160377413-8ae284d4-adcc-4127-8ce1-e2454c43ca1a.png">
