### ISSUE TITLE
Does this library support the new order api?

### ISSUE THREAD

**Issue by eliezerp3** [ectoflow/vue-stripe-js#12]
Dont seem to know whats wrong. I cant seem to get it to work no matter what i try
```
<template>
<div>
    <StripeElements v-slot="{ elements, instance }" ref="paymentElements"
                :stripe-key="appStateStore.clientSettings!.stripePublishableKey" :instance-options="instanceOptions"
                :elements-options="elementsOptions">
                <StripeElement ref="payment" type="payment" :elements="elements" />
     </StripeElements>
     <v-btn @click="pay">Pay</v-btn>
</div>
</template>

<script setup lang="ts">
import { loadStripe } from '@stripe/stripe-js'
import { StripeElement, StripeElements, initStripe } from 'vue-stripe-js'

const s = await loadStripe(
    useAppStateStore().clientSettings!.stripePublishableKey,
    {
        betas: ['process_order_beta_1'],
        apiVersion: "2020-08-27; orders_beta=v4",
    }
);

const paymentElements = ref<any>();

const pay = async () => {
    const v = paymentElements.value!;
    console.log(v.elements);
    try {
        const res = await s!.processOrder({
            elements: v.elements,
            confirmParams: {

                // Return URL where the customer should be redirected after the Order's payment is confirmed.
                return_url: 'http://localhost:3001/order/123/status',
            },
        })
        console.log('RESULT');
        console.log(res);
    } catch (e) {
        console.log('ERROR');
        console.log(e);
    }
}
</script>
```
LOGS
```
ERROR
{}
```
Put all the relevant code in. Anything that is used but not defined there is custom way of getting whats needed so didnt put it in. The order is successfully submitting (200ok) but is not passing the payment method and is throwon gan error with an empty error message

**Comment by softbeehive** [comment]
I haven't found any mention of `processOrder` method in Stripe.js documentation. This library integrates Stripe.js with Vue component lifecycle, that's it. To write your payment flow code you still need to read Stripe.js docs.

I suggest checking https://stripe.com/docs/js

**Comment by eliezerp3** [comment]
@softbeehive  It’s in the docs [here](https://stripe.com/docs/js/orders/process_order#:~:text=stripe.processorder(options))  It’s  part of the order api beta.

**Comment by softbeehive** [comment]
https://stripe.com/docs/orders
> The Orders API is no longer accepting new beta users. If you’re already in the Orders beta, please [sign in](https://dashboard.stripe.com/login) to access the documentation.

We can stop at **beta**. If Stripe didn't make it part of the stable api yet, there must be a good reason for that.
`vue-stripe-js` supports stable Stripe.js v3

**Comment by eliezerp3** [comment]
@softbeehive Ok. As you can tell from the title of this issue; that was literally my whole question; “Does this library support the new order API?”. No need to get so snarky. Have a great day.
