### ISSUE TITLE
Can you provide a full example code with Payment Elements with create a payment intent first (client secret ..)

### ISSUE THREAD

**Issue by Dante690** [ectoflow/vue-stripe-js#14]

**Comment by Dante690** [comment]
thanks for the full description..

**Comment by Dante690** [comment]
Also we need a full payment element guide for this.. like card example...

**Comment by tanha1998** [comment]
> Also we need a full payment element guide for this.. like card example...thnks

![Capture](https://user-images.githubusercontent.com/62093111/199694433-22a3bcd2-7e58-4779-a5ae-81464e1c969e.PNG)

**Comment by tanha1998** [comment]
`await elms.value.instance.confirmCardPayment(clientSecret, {
							payment_method: {
								card: cardNumber
							}
						})`

**Comment by softbeehive** [comment]
https://stripe.com/docs/payments/accept-a-payment?ui=elements

I'm gonna provide a full example, which requires stripe account and payment intent (server-side), but really tight on time right now

Basically, you need `client_secret`, it then passed as property of options to StripeElements. Then you'll be able to call `confirmPayment` on stripe instance.

**Comment by yashBhosale** [comment]
@softbeehive If you wanna assign this to me I can probably submit a PR with an example for using Payment Elements this weekend.

**Comment by softbeehive** [comment]
@yashBhosale you are welcome to submit a PR at any time

Here is some guidance:
1. Create PaymentElement.vue in examples folder
2. Use Vue Composition API (preferably)
3. Test payment type element
4. Add Payment Type section to README.md before "Types"

**Comment by mattvb91** [comment]
does anyone have a working example with payment intent??

**Comment by nickbewley** [comment]
Folks this is a cool package but also really confusing. Can anyone help provide a full example of how one can submit a payment to stripe and redirect to another page afterwards? Thanks so much. Best, Newb

**Comment by softbeehive** [comment]
Payment intent requires server-side code that depends on the language of your choice. I can totally see the value of having comprehensive guide on how to do that. And I can see why people struggle with its complexity.

But I realize this is outside of scope of this package, which has a single goal: integrate stripe.js with vue component lifecycle. The reason I didn't make type="payment" the default is that it requires extra work. I suggest asking Stripe for the vue guide, they have resources and capacity to offer it.

Community projects like this receive little to no support and I'm not first to say this but this is an uncomfortable truth about open-source. If someone is willing to invest time + energy and make the guide centered around vue integration of the payment element, I'm happy to link it in readme. I hope it explains the situation.

**Comment by softbeehive** [comment]
### Quick guide

To start with payment element
1. Grab `clientSecret` from the payment intent
2. Pass it to `elements-options`

```vue
<template>
<StripeElements
  ...
  :elements-options="elementsOptions"
>
  <StripeElement
    type="payment"
    ...
  />
</StripeElements>
<template />
```

```ts
const elementsOptions = ref({
  clientSecret: 'grab_it_from_payment_intent',
  // https://stripe.com/docs/js/elements_object/create#stripe_elements-options
})
```
### Screenshot
<img width="840" alt="image" src="https://github.com/user-attachments/assets/0619f7b5-a70f-48a1-84c4-c75bf9fc6ded" />
