### ISSUE TITLE
Received unknown parameters: type, elements, options, stripeElement

### ISSUE THREAD

**Issue by yk-sgr** [ectoflow/vue-stripe-js#15]
```typescript
const cardNumber = ref<StripeCardNumberElement>();
```

```typescript
elms.value.instance.confirmCardPayment(clientSecret.value, {
  payment_method: {
    billing_details: {
      ...
     },
    card: cardNumber.value,
  }
});
```

When I run this code I receive a 400 on the /confirm endpoint of the stripe API.
`Received unknown parameters: type, elements, options, stripeElement`

**Comment by softbeehive** [comment]
It seems to me that you pass Component instance where it should likely be `stripeElement`. That's my guess, please provide the reproduction link and feel free to reopen
