### ISSUE TITLE
Code clarification

### ISSUE THREAD

**Issue by Shanzid01** [ectoflow/vue-stripe-js#2]
Hi, can you please show me how to add a customer's name and address into the Stripe card element

**Comment by softbeehive** [comment]
Hi, card element options doesn't contain name and address field
https://stripe.com/docs/js/elements_object/create_element?type=card

Payment Element may contain address field depending on the selected payment method, in other words address and customer name are not required for card payment.

Check Payment Request API if you want to handle shipping info
https://stripe.com/docs/js/appendix/shipping_address
