### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by ShirinShirinak** [ectoflow/vue-stripe-js#21]
I tried to install this library but it seems it's not working! The stripe folder inside the node modules is completely empty!

**Comment by softbeehive** [comment]
Hi @ShirinShirinak,
I suggest to check `node_modules/vue-stripe-js`

```bash
npm i vue-stripe-js --save-dev
```

And if you wanna use stripe loader, don't forget to install it
```bash
npm i @stripe/stripe-js --save-dev
```
