### ISSUE TITLE
Updates required in README.md

### ISSUE THREAD

**Issue by murraygunn** [ectoflow/vue-stripe-js#22]
There are two small problems in the instructions that can be quickly addressed.
- Step 1 instructions should include installation of @stripe/stripe-js
- In the sample code in step 3, there's a comma at the end of the following code block that needs causes errors.

>     const pay = () => {
>       // Get stripe element
>       const cardElement = card.value.stripeElement
> 
>       // Access instance methods, e.g. createToken()
>       elms.value.instance.createToken(cardElement).then((result: object) => {
>         // Handle result.error or result.token
>         console.log(result)
>       })
>     },

**Comment by softbeehive** [comment]
Thank you for reporting the issue, fixed in v1.0.2
