### ISSUE TITLE
Could this work with Pricing Tables?

### ISSUE THREAD

**Issue by videovillain** [ectoflow/vue-stripe-js#25]
Currently, I'm trying to get [Pricing Tables](https://stripe.com/docs/payments/checkout/pricing-table) to display, but having a tough time.

Could you implement a way to display Pricing Tables provided by Stripe and their generated embed code?
```
    <script async src="https://js.stripe.com/v3/pricing-table.js"></script>

    <stripe-pricing-table pricing-table-id="prctbl_..." publishable-key="pk_test_...">
    </stripe-pricing-table>
```

Though it seems like it should be intuitive, I don't know how to make the `<stripe-pricing-table>` work.

**Comment by softbeehive** [comment]
Pricing tables is a different API, closing as not relevant
