### ISSUE TITLE
payment Element didn't mount normally

### ISSUE THREAD

**Issue by mirabuck** [ectoflow/vue-stripe-js#26]
Hi there,

Trying to use this library to add a payment element and I keep running into this error: "payment Element didn't mount normally".  Do you have any guidance on what might cause this?

Many thanks!

**Comment by softbeehive** [comment]
Hi,

an actual DOM element is created by the stripe library. You can trace what throws this error. For the payment element suggest:

1. Make sure stripe.js is loaded before you mount vue components
2. Pass the correct type
```vue
<StripeElements
    v-if="stripeLoaded"
    ...
  >
    <StripeElement
      type="payment"
      ...
    />
</StripeElements>
```

For the reference, check the example https://github.com/ectoflow/vue-stripe-js/blob/main/examples/CardOnly.vue

**Comment by bondgeek** [comment]
Thanks @softbeehive  -- that helps.  I'll look through that example.

**Comment by softbeehive** [comment]
You are welcome to add your findings. Feel free to reopen the issue if you believe there is a bug in vue-stripe-js
