### ISSUE TITLE
clientsecret change

### ISSUE THREAD

**Issue by Ischafak** [ectoflow/vue-stripe-js#29]
Hi, actually it is not a issue but i just want to take your opinion. I really need help.

in my project there is promotion codes

when payment page opens i take clientSecret from backend and with that clientsecret stripeelements form loads.
when user applies promotion this process repeats(i take another clientsecret from backend)

my first question is: is this process correct what do you think?
second question is: for now i cant update client secret after promotion how can i change it?
i tried
```
       this.$refs.elms.elements.update({
          clientSecret: this.elementsOptions.clientSecret,
        });
```
this one but it only takes upgrade 1 times (for example user applied promotion and delete promotion afterwards) when user clicks buy. It take the discounted price

if i give :key to stripeelements component form reloads and everything works fine but i dont know is it a good solution or not

**Comment by softbeehive** [comment]
Hi,

if your goal is to update `clientSecret` in the `elementsOptions`, then yes - what you are doing makes sense. Actually, there is a watcher attached to the elementsOptions (reactive object), update method is called automatically on change
https://github.com/ectoflow/vue-stripe-js/blob/main/src/components/StripeElements.vue#L43

However it is absolutely fine in my opinion to call it manually, it it's a good way to learn.

**Comment by softbeehive** [comment]
Check this example: 
https://github.com/ectoflow/vue-stripe-js/blob/a9e4ecc9916bd8475562ac37b39dc89c0b0b73d4/examples/CardOnly.vue#L34-L36
