### ISSUE TITLE
StripeElement.vue `options` are considered optional but generate console warning when left empty

### ISSUE THREAD

**Issue by stevebauman** [ectoflow/vue-stripe-js#5]
When creating the `<StripeElement>` component, the `options` prop is considered optional, but it generates an "Invalid watch source" console warning due to a `watch()` being supplied with a plain object instance via its default value:

https://github.com/ectoflow/vue-stripe-js/blob/ca1f828bc0d5b230927e7b0b37911e90371d0b89/src/components/StripeElement.vue#L33-L35

https://github.com/ectoflow/vue-stripe-js/blob/ca1f828bc0d5b230927e7b0b37911e90371d0b89/src/components/StripeElement.vue#L85-L87

![Screen Shot 2022-05-13 at 12 41 01 PM](https://user-images.githubusercontent.com/6421846/168329016-861d5494-ce59-473b-bebc-3cc07c779ddc.png)

**Comment by softbeehive** [comment]
I think the problem is that you try to watch non-reactive property, I'm pretty sure if you try toRefs on your props the warning will be gone. Note it's a Vue warning, not a typescript

```ts
import { toRefs } from 'vue'
const { options } = toRefs(props)

watch(options, () => {
  // ...
})
```

**Comment by softbeehive** [comment]
Ah, now I got it

**Comment by stevebauman** [comment]
Oh, I'm not watching anything. This is coming from the vue-stripe-js source element. 

Here's my code:

```vue
<StripeElements
    v-if="stripe.ready && stripe.intent"
    ref="elements"
    class="space-y-4"
    #default="{ elements }"
    :stripe-key="stripe.key"
    :elements-options="elementsOptions"
>
    <StripeElement type="payment" :elements="elements"/>
    <!-- No :options configured above. -->
</StripeElements>
```

**Comment by softbeehive** [comment]
I'll take a look, this requires a fix, thanks for reporting

**Comment by stevebauman** [comment]
Happy to help! Let me know if you'd like help testing anything out 👍 

Thanks so much for your work on this package ❤️

**Comment by softbeehive** [comment]
Try version `1.0.1`

**Comment by stevebauman** [comment]
Excellent, works great -- thank you! 🙏
