### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by monkemedia** [ectoflow/vue-stripe-js#7]
Is it possible to use Themes with this component? https://stripe.com/docs/stripe-js/appearance-api#theme

**Comment by scramatte** [comment]
Hi,  it looks that vue elements component, doesn't support appearance and theme.
Can you implement it ?

Regards

**Comment by softbeehive** [comment]
Actually, it works with elements options, no change needed
```vue
<template>
<StripeElements
  ...
  :elements-options="elementsOptions"
>
  <StripeElement
    type="payment"
    ...
  />
</StripeElements>
<template />
```

```ts
const elementsOptions = ref({
  clientSecret: 'grab_it_from_payment_intent',
  appearance: {
    theme: 'night'
  }
  // https://stripe.com/docs/js/elements_object/create#stripe_elements-options
})
```
### Screenshot
<img width="840" alt="image" src="https://github.com/user-attachments/assets/0619f7b5-a70f-48a1-84c4-c75bf9fc6ded" />
