### ISSUE TITLE
How to style Stripe Element?

### ISSUE THREAD

**Issue by jimmiejackson414** [ectoflow/vue-stripe-js#9]
I think I'm misunderstanding how the options transfer to the actual Stripe elements themselves or something. This is what it looks like without any options on page load:
![Screen Shot 2022-06-28 at 11 54 40 AM](https://user-images.githubusercontent.com/93394140/176260486-8c8c1d8d-8e8f-4aa5-afe8-5115dd8c99db.png)
 
Here's how my component looks currently:
```vue
<template>
  <StripeElements
    v-if="stripeLoaded"
    v-slot="{ elements }"
    ref="elms"
    :stripe-key="stripeKey"
    :instance-options="instanceOptions"
    :elements-options="elementsOptions">
    <StripeElement
      ref="card"
      :elements="elements"
      :options="cardOptions" />
  </StripeElements>
  <q-btn
    color="primary"
    @click="pay">
    Pay
  </q-btn>
</template>

<script lang='ts' setup>
  import { onBeforeMount, ref } from 'vue';
  import { loadStripe } from '@stripe/stripe-js';
  import { StripeElements, StripeElement } from 'vue-stripe-js';
  import type { StripeConstructorOptions, StripeElementsOptions } from '@stripe/stripe-js';
  import { colors } from 'quasar';

  const stripeKey = ref(import.meta.env.VITE_STRIPE_PUBLIC_KEY);
  const stripeLoaded = ref(false);
  const card = ref();
  const elms = ref();
  const instanceOptions = ref<StripeConstructorOptions>({
    // https://stripe.com/docs/js/initializing#init_stripe_js-options
  });
  const elementsOptions = ref<StripeElementsOptions>({
    fonts: [{ cssSrc: 'https://fonts.googleapis.com/css2?family=Lato' }],
    locale: 'auto',
    appearance: {
      // theme: 'stripe',
      variables: {
        colorPrimary: colors.getPaletteColor('primary'),
        colorText: '#f00',
      },
    },
    loader: 'auto',
    // https://stripe.com/docs/js/elements_object/create#stripe_elements-options
  });
  const cardOptions = ref({
    // https://stripe.com/docs/stripe.js#element-options
    // value: {
    //   postalCode: '12345',
    // },
  });

  const pay = () => {
    // Get stripe element
    const cardElement = card.value.stripeElement;

    // Access instance methods, e.g. createToken()
    elms.value.instance.createToken(cardElement)
      .then((result: object) => {
        // Handle result.error or result.token
        console.log(result);
      });
  };

  onBeforeMount(() => {
    const stripePromise = loadStripe(stripeKey.value);
    stripePromise.then(() => {
      stripeLoaded.value = true;
    });
  });
</script>
```

I am receiving a console warning: `Unrecognized create() parameter: appearance is not a recognized parameter.`

What's the proper way to go about styling?

EDIT: I noticed that at the very bottom of the README, that it's supposed to be unstyled, and to visit the docs for Element Options to handle styling. I'm trying out everything, however I'm still receiving console warnings about unrecognized parameters?

**Comment by softbeehive** [comment]
Hi,

first thing I noticed: you try to use `appearance` on the wrong type. Since you don't define type on `<StripeElement />` - it's a **card** by default.  Type `payment` supports appearance. But it seems to me that you just want to style card.

So for styling card element you can use:
```
const cardOptions = ref({
  style: {
     iconColor: '#c4f0ff',
     color: '#fff',
  }
})
```
https://stripe.com/docs/js/elements_object/create_element?type=card#elements_create-options-style
https://stripe.com/docs/js/appendix/style

Stripe documentation broke older links, which is a pity for a company like that.

**Comment by softbeehive** [comment]
@stripe, consider supporting this open-source project. It allows people to use Stripe.js with Vue lifecycle hooks with much better DX.
